export const sampleProjects = [
  {
    category: "Multi-residential",
    title: "Contemporary Rental Development",
    image: "/images/projects/built-work/multi-residential-development.jpg",
    location: "Botswana",
    stage: "Design development",
    scope: "Architectural design | Unit planning | Site layout",
    text: "A coordinated multi-unit residential concept shaped around private entrances, covered parking and a clear shared arrival court.",
  },
  {
    category: "Residential",
    title: "Lenganeng Residential Upgrade",
    image: "/images/projects/built-work/lenganeng-residential-design.jpg",
    location: "Lenganeng, Tlokweng",
    stage: "Design + site support",
    scope: "Measured review | Architectural design | Construction support",
    text: "A practical residential upgrade that adds usable accommodation while working carefully with the scale and constraints of the existing plot.",
  },
  {
    category: "Residential",
    title: "Oodi Family Residence",
    image: "/images/projects/built-work/oodi-residence-design.jpg",
    location: "Oodi",
    stage: "Design + construction",
    scope: "Architectural design | Structural coordination | Site inspections",
    text: "A contemporary two-storey family residence developed from coordinated design information through active construction-stage review.",
  },
  {
    category: "Interior design",
    title: "Gaborone North Utility Suite",
    image: "/images/projects/built-work/gaborone-north-laundry-design.jpg",
    location: "Gaborone North",
    stage: "Interior design",
    scope: "Space planning | Joinery design | Technical detailing",
    text: "A compact laundry and utility room planned for generous storage, a durable work surface and straightforward everyday use.",
  },
];
