const imageRoot = "/images/projects/built-work";

export const projectCategories = [
  "All",
  "Residential",
  "Multi-residential",
  "Renovations",
  "Interiors",
  "Technical & site",
];

export const projects = [
  {
    slug: "mahalapye-residential-design",
    category: "Residential",
    title: "Mahalapye Residential Design",
    location: "Mahalapye",
    stage: "Developed design",
    image: `${imageRoot}/mahalapye-residence-model.webp`,
    gallery: [
      `${imageRoot}/mahalapye-residence-model.webp`,
      `${imageRoot}/mahalapye-courtyard-model.webp`,
    ],
    summary: "A courtyard-led home developed through spatial planning, elevation studies, visualisation and coordinated architectural documentation.",
    scope: ["Architectural design", "Site planning", "3D visualisation", "Working drawings"],
    challenge: "Organise a generous residential brief into a coherent plan with sheltered outdoor living and clear movement across the plot.",
    response: "CGM tested the building massing, arrival sequence, courtyard relationships and elevations before progressing the design into coordinated documentation.",
    proof: "Project model views and architectural drawing records",
  },
  {
    slug: "gwest-residential-documentation",
    category: "Multi-residential",
    title: "Gaborone West Residential Scheme",
    location: "Gaborone West",
    stage: "Submission documentation",
    image: `${imageRoot}/gwest-residential-documentation.webp`,
    gallery: [`${imageRoot}/gwest-residential-documentation.webp`],
    summary: "A compact multi-residential layout coordinated through plans, elevations, sections, roof information and construction details.",
    scope: ["Unit planning", "Council drawing package", "Sections and elevations", "Technical details"],
    challenge: "Fit practical rental accommodation and circulation into a constrained urban site while keeping the construction information legible.",
    response: "CGM resolved unit layouts, roof drainage, elevations and key junction details in one coordinated submission set.",
    proof: "Anonymised extract from the coordinated architectural set",
  },
  {
    slug: "contemporary-rental-development",
    category: "Multi-residential",
    title: "Contemporary Rental Development",
    location: "Botswana",
    stage: "Design development",
    image: `${imageRoot}/multi-residential-development.webp`,
    gallery: [`${imageRoot}/multi-residential-development.webp`],
    summary: "A contemporary multi-unit concept balancing private entrances, covered parking, upper-level outdoor space and a clear shared court.",
    scope: ["Development planning", "Unit design", "Parking coordination", "Architectural visualisation"],
    challenge: "Create a strong shared identity without losing the privacy and day-to-day practicality each unit needs.",
    response: "The proposal uses repeated structural bays, screened parking and individual thresholds to make the development read as one place and several homes.",
    proof: "CGM design-development visualisation",
  },
  {
    slug: "tlokweng-multi-residential",
    category: "Multi-residential",
    title: "Tlokweng Multi-Residential Planning",
    location: "Tlokweng",
    stage: "Council documentation",
    image: `${imageRoot}/tlokweng-multi-residential-documentation.webp`,
    gallery: [`${imageRoot}/tlokweng-multi-residential-documentation.webp`],
    summary: "A two-storey rental scheme documented from site planning and unit layouts through elevations, sections and construction details.",
    scope: ["Site planning", "Ground and first-floor plans", "Council submission", "Construction detailing"],
    challenge: "Coordinate multiple units, access and existing site relationships within a clear approval drawing package.",
    response: "CGM brought planning, vertical circulation, elevations and technical information together in a structured submission sheet.",
    proof: "Anonymised extract from the council submission set",
  },
  {
    slug: "phase4-home-extension",
    category: "Renovations",
    title: "Phase 4 Home Extension",
    location: "Gaborone Phase 4",
    stage: "Extension documentation",
    image: `${imageRoot}/phase4-extension-documentation.webp`,
    gallery: [`${imageRoot}/phase4-extension-documentation.webp`],
    summary: "An existing home extended through a coordinated plan that separates retained construction from new work and integrates added living functions.",
    scope: ["Existing-building review", "Extension planning", "Elevations and sections", "Approval documentation"],
    challenge: "Add meaningful accommodation while respecting the existing structure, plot access and established roof geometry.",
    response: "CGM mapped retained and proposed elements, coordinated the new rooms and documented the revised external form for review.",
    proof: "Anonymised extract from the extension drawing package",
  },
  {
    slug: "gaborone-north-utility-suite",
    category: "Interiors",
    title: "Gaborone North Utility Suite",
    location: "Gaborone North",
    stage: "Interior technical design",
    image: `${imageRoot}/gaborone-north-laundry-design.webp`,
    gallery: [`${imageRoot}/gaborone-north-laundry-design.webp`],
    summary: "A compact laundry planned around storage capacity, practical work surfaces, appliance clearances and durable everyday use.",
    scope: ["Interior space planning", "Cabinetry design", "Material direction", "Technical detailing"],
    challenge: "Make a narrow utility room work harder without crowding the sink, appliance and circulation zone.",
    response: "Full-height and overhead storage frame a continuous work area, with a restrained material palette keeping the small room bright.",
    proof: "CGM interior design visualisation and technical package",
  },
  {
    slug: "bespoke-storage-design",
    category: "Interiors",
    title: "Bespoke Storage Design",
    location: "Gaborone",
    stage: "Technical detailing",
    image: `${imageRoot}/wardrobe-technical-design.webp`,
    gallery: [`${imageRoot}/wardrobe-technical-design.webp`],
    summary: "Fitted wardrobe studies translating room dimensions into buildable elevations, internal storage zones and material notes.",
    scope: ["Measured planning", "Joinery elevations", "Internal configuration", "Material specification"],
    challenge: "Use full wall widths efficiently while keeping hanging, shelving and drawer storage easy to manufacture and use.",
    response: "CGM developed front and internal elevations for different wall sizes, with clear module dimensions and support requirements.",
    proof: "Anonymised extract from the joinery detail sheet",
  },
  {
    slug: "gnorth-outdoor-amenity",
    category: "Technical & site",
    title: "Gaborone North Outdoor Amenity",
    location: "Gaborone North",
    stage: "Detailed design",
    image: `${imageRoot}/gnorth-amenity-documentation.webp`,
    gallery: [`${imageRoot}/gnorth-amenity-documentation.webp`],
    summary: "A coordinated gazebo, braai and service-yard study developed through plan, elevation, section and three-dimensional details.",
    scope: ["Outdoor space planning", "Detail design", "Service coordination", "Construction information"],
    challenge: "Combine cooking, seating and service functions in a compact outdoor zone with clear buildable information.",
    response: "CGM documented the overall arrangement and the smaller technical components so site decisions could follow one coordinated design intent.",
    proof: "Anonymised extract from the detailed design package",
  },
  {
    slug: "oodi-residential-coordination",
    category: "Technical & site",
    title: "Oodi Residential Coordination",
    location: "Oodi",
    stage: "Design and site support",
    image: `${imageRoot}/oodi-residence-design.webp`,
    gallery: [
      `${imageRoot}/oodi-residence-design.webp`,
      `${imageRoot}/oodi-site-progress.webp`,
    ],
    summary: "A contemporary residential design supported by construction-stage observations and coordination as work progresses on site.",
    scope: ["Architectural direction", "Technical coordination", "Site observations", "Progress review"],
    challenge: "Protect design intent while responding to the practical questions and sequencing realities that emerge during construction.",
    response: "CGM connects visual design decisions with site evidence, recording progress and clarifying the next technical actions within the appointment.",
    proof: "Design visualisation and site-progress record",
  },
  {
    slug: "lenganeng-residential-upgrade",
    category: "Technical & site",
    title: "Lenganeng Residential Upgrade",
    location: "Lenganeng, Tlokweng",
    stage: "Design and site review",
    image: `${imageRoot}/lenganeng-residential-design.webp`,
    gallery: [
      `${imageRoot}/lenganeng-residential-design.webp`,
      `${imageRoot}/lenganeng-site-progress.webp`,
    ],
    summary: "A residential upgrade combining accommodation planning, architectural visualisation and site-based review of the developing work.",
    scope: ["Measured review", "Architectural design", "Visualisation", "Construction support"],
    challenge: "Add useful residential capacity while working with existing plot conditions and live construction constraints.",
    response: "CGM developed the proposed form, then supported the project with site records and practical coordination as the work advanced.",
    proof: "CGM model view and site-progress record",
  },
];

export const featuredProjects = projects.slice(0, 6);

export function getProject(slug) {
  return projects.find((project) => project.slug === slug);
}
